using Test
include(joinpath(@__DIR__, "distill_interests.jl"))

@testset "url_hash parity with brief-routine.md" begin
    @test url_hash("https://www.example.com/Foo/Bar/") ==
        "e54b9d6f8b4f9ceb3b709a2c5a0cd1da7d7057edb8ce04ea8f0f5fa02af61a31"
    @test url_hash("HTTP://Example.com/a?b=1#frag") ==
        "036cbe16b0015b0a30d733ca981c8ebb80535abe46b862bbb67d0affb9331be7"
    @test url_hash("https://nautil.us/") ==
        "c726d0edc78fe9aeaebc268a06469f3765ed845375543dbff8818ee55eeeeaf6"
    @test url_hash("https://www.MarginalRevolution.com") ==
        "127f69b4e3b0315ae231525be9f24c31fff9d267a16d98a43d0a0721e61f9002"
    @test url_hash("https://example.com/a") == url_hash("HTTP://Example.com/a?b=1#frag")
end

@testset "read_links from fixture db (excludes deleted)" begin
    db = tempname() * ".sqlite"
    run(pipeline(`sqlite3 $db`, stdin = IOBuffer("""
    CREATE TABLE link (url TEXT, title TEXT, author TEXT, starred BOOLEAN NOT NULL,
                       readAt DOUBLE NOT NULL, deletedAt DOUBLE NOT NULL DEFAULT 0);
    INSERT INTO link VALUES ('https://example.com/a','Alpha','',0,100.0,0);
    INSERT INTO link VALUES ('https://www.example.org/b/','Bravo','',1,0.0,0);
    INSERT INTO link VALUES ('http://test.com/c?x=1','Charlie','',0,200.0,0);
    INSERT INTO link VALUES ('https://gone.com/x','Deleted','',0,300.0,5.0);
    """)))
    rows = read_links(db)
    @test length(rows) == 3
    @test Set(r.url for r in rows) ==
        Set(["https://example.com/a","https://www.example.org/b/","http://test.com/c?x=1"])
    @test any(r -> r.starred && r.title == "Bravo", rows)
    rm(db, force = true)
end

@testset "render_hashes sorted-unique" begin
    rows = [(url="https://example.com/a", title="A", author="", starred=false, readAt=1.0),
            (url="https://www.example.org/b/", title="B", author="", starred=true, readAt=0.0),
            (url="http://test.com/c?x=1", title="C", author="", starred=false, readAt=2.0),
            (url="https://example.com/a", title="dup", author="", starred=false, readAt=3.0)]
    @test render_hashes(rows) == join([
        "036cbe16b0015b0a30d733ca981c8ebb80535abe46b862bbb67d0affb9331be7",
        "734f475651f181f8fa848cd5866b65513a22b1b1b7c6a1cd632ef3dacb59d0bb",
        "7e44e3a003133e0ce9f27e2c353dc7f9c2b007e0b79c441d98b2109a98cd2ede",
    ], '\n') * '\n'
end

@testset "pick_exemplars: starred first, then recency" begin
    rows = [(url="u1", title="Charlie", author="", starred=false, readAt=200.0),
            (url="u2", title="Alpha",   author="", starred=false, readAt=100.0),
            (url="u3", title="Bravo",   author="", starred=true,  readAt=0.0),
            (url="u4", title="",        author="", starred=false, readAt=300.0)]
    @test pick_exemplars(rows) == ["Bravo", "Charlie", "Alpha"]
    @test length(pick_exemplars(rows; limit=2)) == 2
end

@testset "update_toml rewrites only the exemplars block" begin
    titles = ["First \"quoted\"", "Second"]
    sample = """
    foo = 1
    # <<exemplars:auto>> — regenerated by distill_interests.jl. Do not edit by hand.
    [exemplars]
    titles = [
      "old",
    ]
    # <<end:exemplars>>
    bar = 2
    """
    updated = update_toml(sample, titles)
    @test occursin("foo = 1", updated)
    @test occursin("bar = 2", updated)
    @test occursin("\"First \\\"quoted\\\"\",", updated)
    @test occursin("\"Second\",", updated)
    @test !occursin("\"old\"", updated)
    @test occursin("# <<end:exemplars>>", updated)
end

@testset "selftest passes" begin
    @test selftest() === nothing
end
