using SHA

function url_hash(u::AbstractString)
    s = strip(u)
    s = replace(s, r"^https?://"i => "")
    s = first(split(s, '#'; limit=2))
    s = first(split(s, '?'; limit=2))
    parts = split(s, '/'; limit=2)
    host = parts[1]
    path = length(parts) > 1 ? parts[2] : ""
    host = replace(lowercase(host), r"^www\." => "")
    path = rstrip(path, '/')
    norm = isempty(path) ? host : host * "/" * path
    return bytes2hex(sha256(String(norm)))
end

function default_db()
    joinpath(homedir(), "Library", "Group Containers",
             "group.com.ngocluu.goodlinks", "Data", "data.sqlite")
end

function read_links(db_path::AbstractString)
    isfile(db_path) || error("GoodLinks DB not found at $db_path")
    uri = "file:$db_path?mode=ro&immutable=1"
    clean(col) = "replace(replace(replace(coalesce($col,''),char(9),' '),char(10),' '),char(13),' ')"
    cols = join(["url", clean("title"), clean("author"), "starred", "readAt"], ", ")
    sql = "SELECT $cols FROM link WHERE deletedAt = 0 ORDER BY readAt DESC;"
    out = read(`sqlite3 -separator $("\t") $uri $sql`, String)
    rows = NamedTuple[]
    for line in split(chomp(out), '\n')
        isempty(line) && continue
        c = split(line, '\t')
        length(c) != 5 && continue
        push!(rows, (url = String(c[1]), title = String(c[2]), author = String(c[3]),
                     starred = c[4] == "1",
                     readAt = something(tryparse(Float64, c[5]), 0.0)))
    end
    return rows
end

function render_hashes(rows)
    hs = sort(unique(url_hash(r.url) for r in rows))
    return isempty(hs) ? "" : join(hs, '\n') * '\n'
end

function pick_exemplars(rows; limit::Int = 8)
    ordered = vcat([r for r in rows if r.starred],
                   [r for r in rows if !r.starred && r.readAt > 0])
    chosen = String[]
    for r in ordered
        t = strip(r.title)
        isempty(t) && continue
        occursin("<<end:exemplars>>", t) && continue
        String(t) in chosen && continue
        push!(chosen, String(t))
        length(chosen) >= limit && break
    end
    return chosen
end

function toml_escape(s::AbstractString)
    e = replace(s, "\\" => "\\\\")
    e = replace(e, "\"" => "\\\"")
    return "\"" * e * "\""
end

function render_exemplars_block(titles)
    io = IOBuffer()
    println(io, "# <<exemplars:auto>> — regenerated by distill_interests.jl. Do not edit by hand.")
    println(io, "[exemplars]")
    println(io, "titles = [")
    for t in titles
        println(io, "  ", toml_escape(t), ",")
    end
    print(io, "]\n# <<end:exemplars>>")
    return String(take!(io))
end

function update_toml(toml::AbstractString, titles)
    pat = r"# <<exemplars:auto>>.*?# <<end:exemplars>>"s
    occursin(pat, toml) || error("exemplars markers not found in interests.toml")
    return replace(toml, pat => render_exemplars_block(titles))
end

function selftest()
    cases = [
        ("https://www.example.com/Foo/Bar/", "e54b9d6f8b4f9ceb3b709a2c5a0cd1da7d7057edb8ce04ea8f0f5fa02af61a31"),
        ("HTTP://Example.com/a?b=1#frag",     "036cbe16b0015b0a30d733ca981c8ebb80535abe46b862bbb67d0affb9331be7"),
        ("https://nautil.us/",                "c726d0edc78fe9aeaebc268a06469f3765ed845375543dbff8818ee55eeeeaf6"),
        ("https://www.MarginalRevolution.com","127f69b4e3b0315ae231525be9f24c31fff9d267a16d98a43d0a0721e61f9002"),
    ]
    for (u, expected) in cases
        got = url_hash(u)
        got == expected || error("url_hash parity FAIL: $u -> $got (expected $expected)")
    end
end

function main(; db = default_db(), repo = pwd())
    selftest()
    rows = read_links(db)
    isempty(rows) && error("no links read from $db; refusing to overwrite ledger")
    hash_text = render_hashes(rows)
    write(joinpath(repo, "goodlinks-hashes.txt"), hash_text)
    titles = pick_exemplars(rows)
    toml_path = joinpath(repo, "interests.toml")
    write(toml_path, update_toml(read(toml_path, String), titles))
    nhash = length(split(chomp(hash_text), '\n'))
    println("distilled $(length(rows)) links -> $nhash hashes, $(length(titles)) exemplars")
end

if abspath(PROGRAM_FILE) == @__FILE__
    main()
end
